### ISSUE TITLE
"Unknown Project" when working with remote files

### ISSUE THREAD

**Issue by daveyjones** [wakatime/coda-wakatime#1]
Coda really shines when you need to edit files directly on a remote server (which makes sense, because Panic is also the maker of Transmit). This is primarily when we use Coda in our shop. Although the time spent in remote files does get tracked, it's always tracked under "Unknown Project". There is no way to create rules because the files are in Coda's cache using random strings.

```
/Library/Caches/Coda 2/6A1F954C-35E2-45C9-A923-4E42A35E1040/server.js
/Library/Caches/Coda 2/E29824C3-49A5-4217-B5FB-3196FC792999/server.js
/Library/Caches/Coda 2/64DC0FB3-2C57-4D19-A94B-BC1AD6F21B94/server.js
```

An acceptable fix would be to use the project specified by the local `.wakatime-project` file when working on remote files belonging to the same site.

**Comment by alanhamlett** [comment]
We can detect the site name from Coda and use that as the project name if it's Unknown. The project would be detected using the [site nickname](https://github.com/panicinc/CodaPluginKit/blob/b28698cb09bf7a63678a5482e84d854527765dbf/Cocoa%20Plug-ins/CodaPlugInsController.h#L237).

**Comment by daveyjones** [comment]
Yes, the site nickname would be ideal!

**Comment by alanhamlett** [comment]
Fixed in v1.0.1.

**Comment by daveyjones** [comment]
Awesome! Trying it out now. I'll let you know if I have any issues.

**Comment by daveyjones** [comment]
Seems to be working great so far. I did have to restart Coda after updating the plugin before it started working.

**Comment by alanhamlett** [comment]
:tada: :+1:
